name: 'Deploy backend staging'
runs:
  using: composite
  steps:
    - name: Build
      shell: bash
      run: echo "Deploy backend staging"

    - name: Env
      shell: bash
      run: echo $MY_ENV

    - name: Env Repo
      shell: bash
      run: echo ${{ vars.MY_VAR }}
