name: Monorepo Workflow

on:
  workflow_dispatch:

jobs:
  determine_services:
    name: Determine affected services
    runs-on: ubuntu-latest
    outputs:
      services: ${{ steps.determine_services.outputs.services }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Determine affected services
        id: determine_services
        run: |
          services=$(./determine_services.sh)
          echo "::set-output name=services::$services"

  build_frontend:
    name: Build frontend
    needs: determine_services
    runs-on: ubuntu-latest
    if: "contains(needs.determine_services.outputs.services, 'frontend')"
    steps:
      - name: Build
        run: echo "Building frontend"

  build_backend:
    name: Build backend
    needs: determine_services
    runs-on: ubuntu-latest
    if: "contains(needs.determine_services.outputs.services, 'backend')"
    steps:
      - name: Build
        run: echo "Building backend"
