name: Monorepo Workflow

on:
  workflow_dispatch:
  push:
    branches:
      - main

env:
  MY_ENV: myenvhein

jobs:
  affected_services:
    name: Determine affected services
    runs-on: ubuntu-latest
    outputs:
      services: ${{ steps.determine_services.outputs.results }}
    steps:
      - name: Determine affected services
        id: determine_services
        uses: mamezou-tech/monorepo-update-checker@v0.1.1
        with:
          projectPaths: |
            frontend:common,frontend
            backend:common,backend

  frontend_staging:
    name: Deploy frontend staging
    needs: affected_services
    runs-on: ubuntu-latest
    if: ${{ fromJSON(needs.affected_services.outputs.services).frontend }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Deploy
        uses: ./.github/actions/deploy_frontend_staging

  frontend_production:
    name: Deploy frontend production
    environment: Frontend-Production
    needs:
      - frontend_staging
    runs-on: ubuntu-latest
    if: always() && !cancelled() && needs.frontend_staging.result == 'success'
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Deploy
        uses: ./.github/actions/deploy_frontend_production

  backend_staging:
    name: Deploy backend staging
    needs: affected_services
    runs-on: ubuntu-latest
    if: ${{ fromJSON(needs.affected_services.outputs.services).backend }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Deploy
        uses: ./.github/actions/deploy_backend_staging

  backend_production:
    name: Deploy backend production
    environment: Backend-Production
    needs:
      - backend_staging
    runs-on: ubuntu-latest
    if: always() && !cancelled() && needs.backend_staging.result == 'success'
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Deploy
        uses: ./.github/actions/deploy_backend_production
